FROM node:22

WORKDIR /app

# Primeiro copia apenas os arquivos de dependências
COPY package.json package-lock.json ./

# Instala dependências (incluindo devDependencies)
RUN npm install --include=dev

# Copia o restante dos arquivos
COPY . .

# Configura a porta do Vite
ENV PORT=5176
EXPOSE 5176

CMD ["npm", "run", "dev"]